export const environment = {
    USER: process.env.CLAUSULAS_PARAGRAFOS_CRUD_USER,
    PASS: process.env.CLAUSULAS_PARAGRAFOS_CRUD_PASS,
    HOST: process.env.CLAUSULAS_PARAGRAFOS_CRUD_HOST,
    PORT: process.env.CLAUSULAS_PARAGRAFOS_CRUD_PORT,
    DB: process.env.CLAUSULAS_PARAGRAFOS_CRUD_DB,
    HTTP_PORT: process.env.CLAUSULAS_PARAGRAFOS_CRUD_HTTP_PORT,
    AUTH_DB: process.env.CLAUSULAS_PARAGRAFOS_CRUD_AUTH_DB
};